theme: jekyll-theme-cayman
title: Sanna Paajoki
description: Testauksesta ja käytettävyydestä innostunut insinööri | Engineer interested in testing and usability
repository: sannapaajoki/sannapaajoki.github.io.git